name: mobile_app
description: "تطبيق الخبر اليمني الإخباري"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  # إدارة الحالة والراوتينج
  get: ^4.6.6

  # قاعدة البيانات السحابية Supabase والمزامنة اللحظية
  supabase_flutter: ^2.5.6

  # الخطوط
  google_fonts: ^6.2.1

  # الأيقونات الحديثة
  lucide_icons: ^0.257.0
  cupertino_icons: ^1.0.8

  # عرض الصور مع التخزين المؤقت (ضروري جداً لتطبيق الأخبار في الموبايل)
  cached_network_image: ^3.3.1

  # التخزين المحلي (لحفظ تفضيلات المستخدم والمحافظة المفضلة)
  shared_preferences: ^2.2.3

  # مشغل الفيديو والصوت إذا كان هناك تقارير مرئية
  url_launcher: ^6.3.0
  timeago: ^3.7.0
  # مشاركة الأخبار عبر واتساب وتيليجرام
  share_plus: ^7.2.2
  hive_flutter: ^1.1.0
  # تنسيق التواريخ والوقت النسبي (منذ 5 دقائق، منذ ساعة)
  intl: ^0.19.0
  hive: ^2.2.3
  # شريط التحديث عند السحب لأسفل
  pull_to_refresh_flutter3: ^2.0.2

  # حركة وانيميشن خفيف لشاشة البداية
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/